services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-minimal-api
    restart: always
    ports:
      - "5120:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=chatminimaldb;User=chatuser;Password=chatpassword!@#
      - AISettings__Provider=LlamaSharp
      - GgufModelSettings__ModelPath=/models/Llama-3.2-3B-Instruct-Q6_K.gguf
    volumes:
      - ./src/Chat.Minimal.Services/models:/models # Mount models directory
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: chat-minimal-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatminimaldb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword!@#
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309" # Mapeia porta 3309 do container para 3309 do host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
